# Generated by Django 6.0.2 on 2026-02-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('past', 'Past Report (Repository)'), ('new', 'New Submission')], default='past', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
