# Generated by Django 6.0.2 on 2026-04-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_report_type_alter_report_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
